# This file was generated by GoReleaser. DO NOT EDIT.
cask "beer" do
  name "beer"
  desc "CLI for managing your JIRA / Gerrit / git workflow."
  homepage "https://github.com/kunickiaj/beer"
  version "0.6.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beer"

  on_macos do
    on_intel do
      url "https://github.com/kunickiaj/beer/releases/download/v#{version}/beer_Darwin_x86_64.tar.gz",
        verified: "github.com/kunickiaj/beer"
      sha256 "11f8175ac7cb634c32ea7d9643a35e157bbee999838f959c2673b7a6e228e315"
    end
    on_arm do
      url "https://github.com/kunickiaj/beer/releases/download/v#{version}/beer_Darwin_arm64.tar.gz",
        verified: "github.com/kunickiaj/beer"
      sha256 "eaf4c2786a25dad4cb535b760e1f0655792eae5978948b6397328ef6a14aba4b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kunickiaj/beer/releases/download/v#{version}/beer_Linux_x86_64.tar.gz",
        verified: "github.com/kunickiaj/beer"
      sha256 "d6388a7f9212efee29151223b49b50232fcfeef9ae9c130d352c06e39407b6cc"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beer"]
  end

  caveats do
    "If macOS blocks execution, run:"
    "  xattr -dr com.apple.quarantine $(which beer)"
  end

  # No zap stanza required
end
